#!/bin/sh

echo "                                                                 "
echo "##teamcity[testSuiteStarted name='All Tests']"
echo ""
echo "#teamcity[testSuiteStarted name='MyTest']"
echo ""
echo "##teamcity[testStarted name='MyTest::testHelloWorld']"
echo "Hello, world"
echo ""
echo "##teamcity[testFinished name='MyTest::testHelloWorld']"
echo ""
echo "##teamcity[testStarted name='MyTest::testAssertEqual']"
echo ""
echo "##teamcity[testFailed name='MyTest::testAssertEqual' message='equality assertion failed' details='- Expected: 2|n- Actual  : 1|n at example.cpp:29|n']"
echo ""
echo "##teamcity[testFinished name='MyTest::testAssertEqual']"
echo ""
echo "##teamcity[testStarted name='MyTest::testNothing']"
echo ""
echo "##teamcity[testFinished name='MyTest::testNothing']"
echo ""
echo "##teamcity[testSuiteFinished name='MyTest']"
echo ""
echo "##teamcity[testSuiteFinished name='All Tests']"
exit 1
